import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const read = path => readFileSync(resolve(root, path), 'utf8')
const manifest = JSON.parse(read('komari-theme.json'))
const packageJson = JSON.parse(read('package.json'))
const config = manifest.configuration?.data

assert.equal(typeof manifest.name, 'string')
assert.match(manifest.short, /^[\w-]+$/)
assert.notEqual(manifest.short, 'default')
assert.equal(manifest.version, packageJson.version)
assert.equal(manifest.configuration?.type, 'managed')
assert.ok(Array.isArray(config), 'managed configuration.data must be an array')

const keys = config.filter(item => item.type !== 'title').map(item => item.key)
assert.equal(new Set(keys).size, keys.length, 'theme setting keys must be unique')
for (const item of config) {
  assert.ok(['title', 'string', 'number', 'select', 'switch', 'richtext'].includes(item.type), `unsupported config type: ${item.type}`)
  if (item.type !== 'title')
    assert.equal(typeof item.key, 'string')
  if (item.type === 'select')
    assert.equal(typeof item.options, 'string')
}

assert.ok(existsSync(resolve(root, 'dist/index.html')), 'dist/index.html is missing; run the build first')
const distIndex = read('dist/index.html')
assert.match(distIndex, /<title>Komari Monitor<\/title>/)
assert.match(distIndex, /<meta name="description" content="A simple server monitor tool\."/)

const rpc = read('src/utils/rpc.ts')
const init = read('src/utils/init.ts')
const pingChart = read('src/components/PingChart.vue')
const nodeResponse = read('src/utils/nodeResponse.ts')
for (const method of ['common:getNodes', 'common:getNodesLatestStatus', 'common:getRecords'])
  assert.ok(`${rpc}\n${init}\n${pingChart}`.includes(method), `missing RPC compatibility method: ${method}`)
assert.match(pingChart, /public:queryMetrics/)
assert.match(pingChart, /isMethodNotFoundError/)
assert.match(pingChart, /fetchLegacyRecords/)
assert.match(rpc, /normalizeUuidCollection/)
assert.match(nodeResponse, /Array\.isArray\(collection\)/)
assert.match(nodeResponse, /normalized\[uuid\] = item/)

const loadingCover = read('src/components/LoadingCover.vue')
assert.match(loadingCover, /<NodeEarthGlobe/)
assert.match(loadingCover, /variant="intro"/)
assert.match(loadingCover, /brandLogoUrl/)
assert.match(loadingCover, /object-fit:\s*contain/)
assert.match(loadingCover, /prefers-reduced-motion/)
assert.match(loadingCover, /LIVE TOPOLOGY SYNCHRONIZATION/)
assert.match(loadingCover, /lnl-intro-ocean/)

const background = read('src/components/Background.vue')
const dataOcean = read('src/components/DataOcean.vue')
const app = read('src/App.vue')
const header = read('src/components/Header.vue')
const footer = read('src/components/Footer.vue')
const visitorInfo = read('src/components/VisitorInfoCard.vue')
const appStore = read('src/stores/app.ts')
const mainSource = read('src/main.ts')
const provider = read('src/components/Provider.vue')
const serviceWorker = read('public/sw.js')
const earthGlobe = read('src/components/NodeEarthGlobe.vue')
const nodeGeneralCards = read('src/components/NodeGeneralCards.vue')
assert.match(background, /lnl-background-ocean/)
assert.match(background, /lnl-background-depth/)
assert.match(background, /<DataOcean/)
assert.doesNotMatch(background, /telemetryLanes|lnl-data-lane|lnl-background-data-ocean/)
assert.match(dataOcean, /requestAnimationFrame/)
assert.match(dataOcean, /quadraticCurveTo/)
assert.match(dataOcean, /prefers-reduced-motion/)
assert.match(dataOcean, /saveData/)
assert.doesNotMatch(dataOcean, /NODE:|TELEMETRY|DATA STREAM/)
// The intro session key changes only when the intro itself is intentionally
// redesigned; ordinary patch releases must not replay it for every visitor.
assert.match(app, /leonetlab:intro:1\.2\.0/)
assert.match(app, /appShellMounted/)
assert.match(app, /@after-leave="handleIntroAfterLeave"/)
assert.match(app, /preloadHomeVisuals/)
assert.match(app, /introRevealActive/)
assert.match(header, /自动（北京时间）/)
assert.match(header, /resolveThemeMode/)
assert.match(header, /lnl-theme-wipe/)
assert.match(header, /lnl-route-cover/)
assert.match(footer, /<VisitorInfoCard/)
assert.match(visitorInfo, /position:\s*fixed/)
assert.match(visitorInfo, /aria-expanded/)
assert.match(visitorInfo, /身份信息扫描/)
assert.match(visitorInfo, /visitor-scan-beam/)
assert.match(visitorInfo, /compacting/)
assert.match(visitorInfo, /height 440ms/)
assert.doesNotMatch(visitorInfo, /width 760ms/)
assert.doesNotMatch(visitorInfo, /backdrop-filter:\s*blur\(16px\)/)
assert.match(footer, /github\.com\/fangleo5592-prog\/komari-theme-leonetlab/)
assert.match(earthGlobe, /AUTO_ROTATION_RADIANS_PER_MS\s*\*\s*Math\.min\(delta/)
assert.match(earthGlobe, /handleFlagError/)
assert.match(earthGlobe, /object-fit:\s*contain/)
assert.match(earthGlobe, /is-dragging[\s\S]*transition:\s*none/)
assert.doesNotMatch(earthGlobe, /watch\(\(\) => appStore\.isDark,[\s\S]{0,180}rebuildGlobe/)
assert.match(earthGlobe, /globe\.update\(\{[\s\S]{0,180}mapBrightness/)
assert.match(nodeGeneralCards, /data-finance-popover/)
assert.match(nodeGeneralCards, /width:\s*calc\(200% \+ 8px\)/)
assert.match(nodeGeneralCards, /max-width:\s*calc\(100vw - 32px\)/)
assert.match(appStore, /leonetlab:appearance:user-override/)
assert.match(appStore, /!hasThemeModeOverride\.value/)
assert.match(mainSource, /controllerchange/)
assert.match(mainSource, /registration\.update\(\)/)
assert.match(provider, /application\/manifest\+json/)
assert.match(provider, /brandLogoUrl/)
assert.match(serviceWorker, /leonetlab-observatory-v1\.2\.0/)
assert.ok(['brandName', 'brandShortName', 'brandLogoUrl', 'brandHeroTitle', 'brandIntroSubtitle'].every(key => keys.includes(key)))
assert.match(read('index.html'), /rel="icon" href="\/favicon\.ico"/)
assert.match(read('public/robots.txt'), /Disallow:\s*\/admin/)
assert.match(read('public/llms.txt'), /^# Komari Network Observatory/m)

const nodeCard = read('src/components/NodeCard.vue')
const nodePingDisplay = read('src/composables/useNodePingDisplay.ts')
const nodePingStats = read('src/composables/useNodePingStats.ts')
const pingChartSource = read('src/components/PingChart.vue')
const compatibilityTest = read('scripts/test-node-compat.mjs')
const smokeTest = read('scripts/smoke-komari-1.2.5.mjs')
assert.doesNotMatch(nodeCard, /min-height:\s*354px/)
assert.match(nodeCard, /data-node-ping-panel="latency"/)
assert.match(nodeCard, /flex h-8 cursor-pointer flex-col/)
assert.match(nodeCard, /data-node-ping-bar/)
assert.match(nodeCard, /repeat\(\$\{latencyRenderBars\.length\}/)
assert.match(nodePingDisplay, /RECENT_PING_RECORDS_QUERY_HOURS\s*=\s*1/)
assert.doesNotMatch(nodePingDisplay, /latestPing/)
assert.match(nodePingStats, /PING_RECORD_REFRESH_INTERVAL_MS\s*=\s*30_000/)
assert.match(pingChartSource, /PING_DIALOG_REFRESH_INTERVAL_MS\s*=\s*30_000/)
assert.match(pingChartSource, /lnl-ping-workspace/)
assert.match(pingChartSource, /repeat\(auto-fit, minmax\(98px, 1fr\)\)/)
assert.match(pingChartSource, /scale:\s*true/)
assert.doesNotMatch(pingChartSource, /-32603/)
assert.match(compatibilityTest, /1\.2\.5-fix2/)
assert.match(smokeTest, /auditMobileFinanceOverflow/)
assert.match(smokeTest, /documentWidth <= result\?\.viewportWidth/)
assert.match(smokeTest, /auditPingBarGeometry/)
assert.match(smokeTest, /bar\.width >= 2 && bar\.height >= 6/)
assert.match(smokeTest, /auditConfiguredThemeMode/)
assert.match(smokeTest, /auditMobileProbeMatrix/)
assert.match(smokeTest, /auditVisitorCollapse/)

const webManifest = JSON.parse(read('public/manifest.webmanifest'))
assert.equal(webManifest.display, 'standalone')
assert.ok(webManifest.icons.some(icon => icon.sizes === '192x192'))
assert.ok(webManifest.icons.some(icon => icon.sizes === '512x512'))
assert.ok(existsSync(resolve(root, 'dist/sw.js')), 'dist/sw.js is missing')
assert.ok(existsSync(resolve(root, 'dist/offline.html')), 'dist/offline.html is missing')

console.log('LeoNetLab theme validation passed.')
